/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAftAndNotAfterand extends PAfterand
{
    private TNot _not_;
    private PAfternot _afternot_;

    public AAftAndNotAfterand()
    {
    }

    public AAftAndNotAfterand(
        TNot _not_,
        PAfternot _afternot_)
    {
        setNot(_not_);

        setAfternot(_afternot_);

    }
    public Object clone()
    {
        return new AAftAndNotAfterand(
            (TNot) cloneNode(_not_),
            (PAfternot) cloneNode(_afternot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAftAndNotAfterand(this);
    }

    public TNot getNot()
    {
        return _not_;
    }

    public void setNot(TNot node)
    {
        if(_not_ != null)
        {
            _not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _not_ = node;
    }

    public PAfternot getAfternot()
    {
        return _afternot_;
    }

    public void setAfternot(PAfternot node)
    {
        if(_afternot_ != null)
        {
            _afternot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _afternot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_not_)
            + toString(_afternot_);
    }

    void removeChild(Node child)
    {
        if(_not_ == child)
        {
            _not_ = null;
            return;
        }

        if(_afternot_ == child)
        {
            _afternot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(_afternot_ == oldChild)
        {
            setAfternot((PAfternot) newChild);
            return;
        }

    }
}
