/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArithmeticExpressionExpression extends PExpression
{
    private PExpression _lex_;
    private POperators _operators_;
    private PExpression _rex_;

    public AArithmeticExpressionExpression()
    {
    }

    public AArithmeticExpressionExpression(
        PExpression _lex_,
        POperators _operators_,
        PExpression _rex_)
    {
        setLex(_lex_);

        setOperators(_operators_);

        setRex(_rex_);

    }
    public Object clone()
    {
        return new AArithmeticExpressionExpression(
            (PExpression) cloneNode(_lex_),
            (POperators) cloneNode(_operators_),
            (PExpression) cloneNode(_rex_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArithmeticExpressionExpression(this);
    }

    public PExpression getLex()
    {
        return _lex_;
    }

    public void setLex(PExpression node)
    {
        if(_lex_ != null)
        {
            _lex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lex_ = node;
    }

    public POperators getOperators()
    {
        return _operators_;
    }

    public void setOperators(POperators node)
    {
        if(_operators_ != null)
        {
            _operators_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operators_ = node;
    }

    public PExpression getRex()
    {
        return _rex_;
    }

    public void setRex(PExpression node)
    {
        if(_rex_ != null)
        {
            _rex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rex_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lex_)
            + toString(_operators_)
            + toString(_rex_);
    }

    void removeChild(Node child)
    {
        if(_lex_ == child)
        {
            _lex_ = null;
            return;
        }

        if(_operators_ == child)
        {
            _operators_ = null;
            return;
        }

        if(_rex_ == child)
        {
            _rex_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lex_ == oldChild)
        {
            setLex((PExpression) newChild);
            return;
        }

        if(_operators_ == oldChild)
        {
            setOperators((POperators) newChild);
            return;
        }

        if(_rex_ == oldChild)
        {
            setRex((PExpression) newChild);
            return;
        }

    }
}
