/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStatement extends PStatement
{
    private final LinkedList<TTab> _tab_ = new LinkedList<TTab>();
    private TId _id_;
    private TEq _eq_;
    private PExpression _expression_;

    public AAssignStatement()
    {
        // Constructor
    }

    public AAssignStatement(
        @SuppressWarnings("hiding") List<?> _tab_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setTab(_tab_);

        setId(_id_);

        setEq(_eq_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStatement(
            cloneList(this._tab_),
            cloneNode(this._id_),
            cloneNode(this._eq_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStatement(this);
    }

    public LinkedList<TTab> getTab()
    {
        return this._tab_;
    }

    public void setTab(List<?> list)
    {
        for(TTab e : this._tab_)
        {
            e.parent(null);
        }
        this._tab_.clear();

        for(Object obj_e : list)
        {
            TTab e = (TTab) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._tab_.add(e);
        }
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tab_)
            + toString(this._id_)
            + toString(this._eq_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tab_.remove(child))
        {
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TTab> i = this._tab_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TTab) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
