/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ADoubleQuotesValueno extends PValueno
{
    private TStringDoubleQuotes _stringDoubleQuotes_;

    public ADoubleQuotesValueno()
    {
    }

    public ADoubleQuotesValueno(
        TStringDoubleQuotes _stringDoubleQuotes_)
    {
        setStringDoubleQuotes(_stringDoubleQuotes_);

    }
    public Object clone()
    {
        return new ADoubleQuotesValueno(
            (TStringDoubleQuotes) cloneNode(_stringDoubleQuotes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleQuotesValueno(this);
    }

    public TStringDoubleQuotes getStringDoubleQuotes()
    {
        return _stringDoubleQuotes_;
    }

    public void setStringDoubleQuotes(TStringDoubleQuotes node)
    {
        if(_stringDoubleQuotes_ != null)
        {
            _stringDoubleQuotes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stringDoubleQuotes_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stringDoubleQuotes_);
    }

    void removeChild(Node child)
    {
        if(_stringDoubleQuotes_ == child)
        {
            _stringDoubleQuotes_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stringDoubleQuotes_ == oldChild)
        {
            setStringDoubleQuotes((TStringDoubleQuotes) newChild);
            return;
        }

    }
}
