/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ADssComparison extends PComparison
{
    private PAfteror _afteror_;

    public ADssComparison()
    {
    }

    public ADssComparison(
        PAfteror _afteror_)
    {
        setAfteror(_afteror_);

    }
    public Object clone()
    {
        return new ADssComparison(
            (PAfteror) cloneNode(_afteror_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADssComparison(this);
    }

    public PAfteror getAfteror()
    {
        return _afteror_;
    }

    public void setAfteror(PAfteror node)
    {
        if(_afteror_ != null)
        {
            _afteror_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _afteror_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_afteror_);
    }

    void removeChild(Node child)
    {
        if(_afteror_ == child)
        {
            _afteror_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_afteror_ == oldChild)
        {
            setAfteror((PAfteror) newChild);
            return;
        }

    }
}
