/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFuncCallFunctionCall extends PFunctionCall
{
    private PId _id_;
    private final LinkedList _arglist_ = new TypedLinkedList(new Arglist_Cast());

    public AFuncCallFunctionCall()
    {
    }

    public AFuncCallFunctionCall(
        PId _id_,
        List _arglist_)
    {
        setId(_id_);

        {
            this._arglist_.clear();
            this._arglist_.addAll(_arglist_);
        }

    }
    public Object clone()
    {
        return new AFuncCallFunctionCall(
            (PId) cloneNode(_id_),
            cloneList(_arglist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncCallFunctionCall(this);
    }

    public PId getId()
    {
        return _id_;
    }

    public void setId(PId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getArglist()
    {
        return _arglist_;
    }

    public void setArglist(List list)
    {
        _arglist_.clear();
        _arglist_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_arglist_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_arglist_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((PId) newChild);
            return;
        }

        for(ListIterator i = _arglist_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Arglist_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArglist node = (PArglist) o;

            if((node.parent() != null) &&
                (node.parent() != AFuncCallFunctionCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFuncCallFunctionCall.this))
            {
                node.parent(AFuncCallFunctionCall.this);
            }

            return node;
        }
    }
}
