/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMineqqAsMineqDiveq extends PAsMineqDiveq
{
    private TMineq _mineq_;

    public AMineqqAsMineqDiveq()
    {
    }

    public AMineqqAsMineqDiveq(
        TMineq _mineq_)
    {
        setMineq(_mineq_);

    }
    public Object clone()
    {
        return new AMineqqAsMineqDiveq(
            (TMineq) cloneNode(_mineq_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMineqqAsMineqDiveq(this);
    }

    public TMineq getMineq()
    {
        return _mineq_;
    }

    public void setMineq(TMineq node)
    {
        if(_mineq_ != null)
        {
            _mineq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mineq_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_mineq_);
    }

    void removeChild(Node child)
    {
        if(_mineq_ == child)
        {
            _mineq_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_mineq_ == oldChild)
        {
            setMineq((TMineq) newChild);
            return;
        }

    }
}
