/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APlplCalculation extends PCalculation
{
    private PExpression _expression_;
    private TPlusplus _plusplus_;

    public APlplCalculation()
    {
    }

    public APlplCalculation(
        PExpression _expression_,
        TPlusplus _plusplus_)
    {
        setExpression(_expression_);

        setPlusplus(_plusplus_);

    }
    public Object clone()
    {
        return new APlplCalculation(
            (PExpression) cloneNode(_expression_),
            (TPlusplus) cloneNode(_plusplus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlplCalculation(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public TPlusplus getPlusplus()
    {
        return _plusplus_;
    }

    public void setPlusplus(TPlusplus node)
    {
        if(_plusplus_ != null)
        {
            _plusplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plusplus_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_plusplus_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_plusplus_ == child)
        {
            _plusplus_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(_plusplus_ == oldChild)
        {
            setPlusplus((TPlusplus) newChild);
            return;
        }

    }
}
