/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APowerPower extends PPower
{
    private PPower _power_;
    private TPow _pow_;
    private PSomething _something_;

    public APowerPower()
    {
    }

    public APowerPower(
        PPower _power_,
        TPow _pow_,
        PSomething _something_)
    {
        setPower(_power_);

        setPow(_pow_);

        setSomething(_something_);

    }
    public Object clone()
    {
        return new APowerPower(
            (PPower) cloneNode(_power_),
            (TPow) cloneNode(_pow_),
            (PSomething) cloneNode(_something_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPowerPower(this);
    }

    public PPower getPower()
    {
        return _power_;
    }

    public void setPower(PPower node)
    {
        if(_power_ != null)
        {
            _power_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _power_ = node;
    }

    public TPow getPow()
    {
        return _pow_;
    }

    public void setPow(TPow node)
    {
        if(_pow_ != null)
        {
            _pow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pow_ = node;
    }

    public PSomething getSomething()
    {
        return _something_;
    }

    public void setSomething(PSomething node)
    {
        if(_something_ != null)
        {
            _something_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _something_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_power_)
            + toString(_pow_)
            + toString(_something_);
    }

    void removeChild(Node child)
    {
        if(_power_ == child)
        {
            _power_ = null;
            return;
        }

        if(_pow_ == child)
        {
            _pow_ = null;
            return;
        }

        if(_something_ == child)
        {
            _something_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_power_ == oldChild)
        {
            setPower((PPower) newChild);
            return;
        }

        if(_pow_ == oldChild)
        {
            setPow((TPow) newChild);
            return;
        }

        if(_something_ == oldChild)
        {
            setSomething((PSomething) newChild);
            return;
        }

    }
}
