/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class Start extends Node
{
    private PProgramme _pProgramme_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PProgramme _pProgramme_,
        EOF _eof_)
    {
        setPProgramme(_pProgramme_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PProgramme) cloneNode(_pProgramme_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PProgramme getPProgramme()
    {
        return _pProgramme_;
    }

    public void setPProgramme(PProgramme node)
    {
        if(_pProgramme_ != null)
        {
            _pProgramme_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pProgramme_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pProgramme_ == child)
        {
            _pProgramme_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pProgramme_ == oldChild)
        {
            setPProgramme((PProgramme) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pProgramme_) +
            toString(_eof_);
    }
}
