/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDiveq extends Token
{
    public TDiveq()
    {
        super.setText("/=");
    }

    public TDiveq(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDiveq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDiveq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDiveq text.");
    }
}
