/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class TMin extends Token
{
    public TMin()
    {
        super.setText("min");
    }

    public TMin(int line, int pos)
    {
        super.setText("min");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMin(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMin(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMin text.");
    }
}
