/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class TMineq extends Token
{
    public TMineq()
    {
        super.setText("-=");
    }

    public TMineq(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMineq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMineq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMineq text.");
    }
}
