/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMulteq extends Token
{
    public TMulteq()
    {
        super.setText("*=");
    }

    public TMulteq(int line, int pos)
    {
        super.setText("*=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMulteq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMulteq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMulteq text.");
    }
}
