/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class TNone extends Token
{
    public TNone()
    {
        super.setText("None");
    }

    public TNone(int line, int pos)
    {
        super.setText("None");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNone(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNone(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNone text.");
    }
}
