/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TPluseq extends Token
{
    public TPluseq()
    {
        super.setText("+=");
    }

    public TPluseq(int line, int pos)
    {
        super.setText("+=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPluseq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPluseq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPluseq text.");
    }
}
