/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TPow extends Token
{
    public TPow()
    {
        super.setText("**");
    }

    public TPow(int line, int pos)
    {
        super.setText("**");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPow(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPow(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPow text.");
    }
}
