/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(4), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(6), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(6), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(6), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(6), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(6), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(6), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(7), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(7), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(8), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(8), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(9), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(10), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(10), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(10), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(10), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(10), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(10), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(10), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(10), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(11), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(11), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(12), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(12), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(13), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(13), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(13), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(13), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(13), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(14), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(14), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(14), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(14), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(14), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(14), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(14), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(15), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(15), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(15), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(16), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(16), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(16), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(16), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(16), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(17), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(17), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(18), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(18), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(19), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(19), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(20), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(20), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new AGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new AGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFuncCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TDef tdefNode2;
        TId tidNode3;
        TLPar tlparNode4;
        Object nullNode5 = null;
        TRPar trparNode6;
        TSemi tsemiNode7;
        PStatement pstatementNode8;
        tdefNode2 = (TDef)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tlparNode4 = (TLPar)nodeArrayList3.get(0);
        trparNode6 = (TRPar)nodeArrayList4.get(0);
        tsemiNode7 = (TSemi)nodeArrayList5.get(0);
        pstatementNode8 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new ADedeFunction(tdefNode2, tidNode3, tlparNode4, null, trparNode6, tsemiNode7, pstatementNode8);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TDef tdefNode2;
        TId tidNode3;
        TLPar tlparNode4;
        PArgument pargumentNode5;
        TRPar trparNode6;
        TSemi tsemiNode7;
        PStatement pstatementNode8;
        tdefNode2 = (TDef)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tlparNode4 = (TLPar)nodeArrayList3.get(0);
        pargumentNode5 = (PArgument)nodeArrayList4.get(0);
        trparNode6 = (TRPar)nodeArrayList5.get(0);
        tsemiNode7 = (TSemi)nodeArrayList6.get(0);
        pstatementNode8 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new ADedeFunction(tdefNode2, tidNode3, tlparNode4, pargumentNode5, trparNode6, tsemiNode7, pstatementNode8);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AFrfrfArgument(tidNode2, null, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PAssignValue passignvalueNode3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
        {
        }

        pargumentNode1 = new AFrfrfArgument(tidNode2, passignvalueNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AFrfrfArgument(tidNode2, null, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PAssignValue passignvalueNode3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AFrfrfArgument(tidNode2, passignvalueNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCiav pciavNode1;
        {
        TComma tcommaNode2;
        TId tidNode3;
        Object nullNode4 = null;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pciavNode1 = new AFfCiav(tcommaNode2, tidNode3, null);
        }
	nodeList.add(pciavNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCiav pciavNode1;
        {
        TComma tcommaNode2;
        TId tidNode3;
        PAssignValue passignvalueNode4;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        passignvalueNode4 = (PAssignValue)nodeArrayList3.get(0);

        pciavNode1 = new AFfCiav(tcommaNode2, tidNode3, passignvalueNode4);
        }
	nodeList.add(pciavNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignValue passignvalueNode1;
        {
        TAssign tassignNode2;
        PValue pvalueNode3;
        tassignNode2 = (TAssign)nodeArrayList1.get(0);
        pvalueNode3 = (PValue)nodeArrayList2.get(0);

        passignvalueNode1 = new AFrfrfrrfrfAssignValue(tassignNode2, pvalueNode3);
        }
	nodeList.add(passignvalueNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TIf tifNode3;
        PComparison pcomparisonNode4;
        TSemi tsemiNode5;
        PStatement pstatementNode6;
        {
        }
        tifNode3 = (TIf)nodeArrayList1.get(0);
        pcomparisonNode4 = (PComparison)nodeArrayList2.get(0);
        tsemiNode5 = (TSemi)nodeArrayList3.get(0);
        pstatementNode6 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatementStatement(listNode2, tifNode3, pcomparisonNode4, tsemiNode5, pstatementNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TIf tifNode4;
        PComparison pcomparisonNode5;
        TSemi tsemiNode6;
        PStatement pstatementNode7;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tifNode4 = (TIf)nodeArrayList2.get(0);
        pcomparisonNode5 = (PComparison)nodeArrayList3.get(0);
        tsemiNode6 = (TSemi)nodeArrayList4.get(0);
        pstatementNode7 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatementStatement(listNode3, tifNode4, pcomparisonNode5, tsemiNode6, pstatementNode7);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TWhile twhileNode3;
        PComparison pcomparisonNode4;
        TSemi tsemiNode5;
        PStatement pstatementNode6;
        {
        }
        twhileNode3 = (TWhile)nodeArrayList1.get(0);
        pcomparisonNode4 = (PComparison)nodeArrayList2.get(0);
        tsemiNode5 = (TSemi)nodeArrayList3.get(0);
        pstatementNode6 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatementStatement(listNode2, twhileNode3, pcomparisonNode4, tsemiNode5, pstatementNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TWhile twhileNode4;
        PComparison pcomparisonNode5;
        TSemi tsemiNode6;
        PStatement pstatementNode7;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        twhileNode4 = (TWhile)nodeArrayList2.get(0);
        pcomparisonNode5 = (PComparison)nodeArrayList3.get(0);
        tsemiNode6 = (TSemi)nodeArrayList4.get(0);
        pstatementNode7 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatementStatement(listNode3, twhileNode4, pcomparisonNode5, tsemiNode6, pstatementNode7);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TId tidNode3;
        TIn tinNode4;
        TId tidNode5;
        TSemi tsemiNode6;
        PStatement pstatementNode7;
        {
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tinNode4 = (TIn)nodeArrayList2.get(0);
        tidNode5 = (TId)nodeArrayList3.get(0);
        tsemiNode6 = (TSemi)nodeArrayList4.get(0);
        pstatementNode7 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AForStatementStatement(listNode2, tidNode3, tinNode4, tidNode5, tsemiNode6, pstatementNode7);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TId tidNode4;
        TIn tinNode5;
        TId tidNode6;
        TSemi tsemiNode7;
        PStatement pstatementNode8;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tinNode5 = (TIn)nodeArrayList3.get(0);
        tidNode6 = (TId)nodeArrayList4.get(0);
        tsemiNode7 = (TSemi)nodeArrayList5.get(0);
        pstatementNode8 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatementStatement(listNode3, tidNode4, tinNode5, tidNode6, tsemiNode7, pstatementNode8);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TReturn treturnNode3;
        PExpression pexpressionNode4;
        {
        }
        treturnNode3 = (TReturn)nodeArrayList1.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatementStatement(listNode2, treturnNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TReturn treturnNode4;
        PExpression pexpressionNode5;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        treturnNode4 = (TReturn)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatementStatement(listNode3, treturnNode4, pexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TPrint tprintNode3;
        PExpression pexpressionNode4;
        Object nullNode5 = null;
        {
        }
        tprintNode3 = (TPrint)nodeArrayList1.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new APrintStatementStatement(listNode2, tprintNode3, pexpressionNode4, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TPrint tprintNode4;
        PExpression pexpressionNode5;
        Object nullNode6 = null;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tprintNode4 = (TPrint)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new APrintStatementStatement(listNode3, tprintNode4, pexpressionNode5, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TPrint tprintNode3;
        PExpression pexpressionNode4;
        PCommaExpression pcommaexpressionNode5;
        {
        }
        tprintNode3 = (TPrint)nodeArrayList1.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList2.get(0);
        pcommaexpressionNode5 = (PCommaExpression)nodeArrayList3.get(0);

        pstatementNode1 = new APrintStatementStatement(listNode2, tprintNode3, pexpressionNode4, pcommaexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TPrint tprintNode4;
        PExpression pexpressionNode5;
        PCommaExpression pcommaexpressionNode6;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tprintNode4 = (TPrint)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);
        pcommaexpressionNode6 = (PCommaExpression)nodeArrayList4.get(0);

        pstatementNode1 = new APrintStatementStatement(listNode3, tprintNode4, pexpressionNode5, pcommaexpressionNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TId tidNode3;
        TAssign tassignNode4;
        PExpression pexpressionNode5;
        {
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tassignNode4 = (TAssign)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(listNode2, tidNode3, tassignNode4, pexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TId tidNode4;
        TAssign tassignNode5;
        PExpression pexpressionNode6;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tassignNode5 = (TAssign)nodeArrayList3.get(0);
        pexpressionNode6 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssignStatement(listNode3, tidNode4, tassignNode5, pexpressionNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TId tidNode3;
        TMineq tmineqNode4;
        PExpression pexpressionNode5;
        {
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tmineqNode4 = (TMineq)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AIdMineqStatement(listNode2, tidNode3, tmineqNode4, pexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TId tidNode4;
        TMineq tmineqNode5;
        PExpression pexpressionNode6;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tmineqNode5 = (TMineq)nodeArrayList3.get(0);
        pexpressionNode6 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AIdMineqStatement(listNode3, tidNode4, tmineqNode5, pexpressionNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TId tidNode3;
        TDiveq tdiveqNode4;
        PExpression pexpressionNode5;
        {
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tdiveqNode4 = (TDiveq)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AIdDiveqStatement(listNode2, tidNode3, tdiveqNode4, pexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TId tidNode4;
        TDiveq tdiveqNode5;
        PExpression pexpressionNode6;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tdiveqNode5 = (TDiveq)nodeArrayList3.get(0);
        pexpressionNode6 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AIdDiveqStatement(listNode3, tidNode4, tdiveqNode5, pexpressionNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TId tidNode3;
        TLBr tlbrNode4;
        PExpression pexpressionNode5;
        TRBr trbrNode6;
        TAssign tassignNode7;
        PExpression pexpressionNode8;
        {
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tlbrNode4 = (TLBr)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);
        trbrNode6 = (TRBr)nodeArrayList4.get(0);
        tassignNode7 = (TAssign)nodeArrayList5.get(0);
        pexpressionNode8 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new APinakasStatement(listNode2, tidNode3, tlbrNode4, pexpressionNode5, trbrNode6, tassignNode7, pexpressionNode8);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TId tidNode4;
        TLBr tlbrNode5;
        PExpression pexpressionNode6;
        TRBr trbrNode7;
        TAssign tassignNode8;
        PExpression pexpressionNode9;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tlbrNode5 = (TLBr)nodeArrayList3.get(0);
        pexpressionNode6 = (PExpression)nodeArrayList4.get(0);
        trbrNode7 = (TRBr)nodeArrayList5.get(0);
        tassignNode8 = (TAssign)nodeArrayList6.get(0);
        pexpressionNode9 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new APinakasStatement(listNode3, tidNode4, tlbrNode5, pexpressionNode6, trbrNode7, tassignNode8, pexpressionNode9);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TAssert tassertNode3;
        PExpression pexpressionNode4;
        Object nullNode5 = null;
        {
        }
        tassertNode3 = (TAssert)nodeArrayList1.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AAssertionStatement(listNode2, tassertNode3, pexpressionNode4, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TAssert tassertNode4;
        PExpression pexpressionNode5;
        Object nullNode6 = null;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tassertNode4 = (TAssert)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertionStatement(listNode3, tassertNode4, pexpressionNode5, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        TAssert tassertNode3;
        PExpression pexpressionNode4;
        PCommaExpression pcommaexpressionNode5;
        {
        }
        tassertNode3 = (TAssert)nodeArrayList1.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList2.get(0);
        pcommaexpressionNode5 = (PCommaExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertionStatement(listNode2, tassertNode3, pexpressionNode4, pcommaexpressionNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        TAssert tassertNode4;
        PExpression pexpressionNode5;
        PCommaExpression pcommaexpressionNode6;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tassertNode4 = (TAssert)nodeArrayList2.get(0);
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);
        pcommaexpressionNode6 = (PCommaExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssertionStatement(listNode3, tassertNode4, pexpressionNode5, pcommaexpressionNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        PFunctionCall pfunctioncallNode3;
        {
        }
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFuncCallStatement(listNode2, pfunctioncallNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        PFunctionCall pfunctioncallNode4;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        pfunctioncallNode4 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFuncCallStatement(listNode3, pfunctioncallNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        TLPar tlparNode3;
        Object nullNode4 = null;
        TRPar trparNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        trparNode5 = (TRPar)nodeArrayList3.get(0);

        pfunctioncallNode1 = new AEreaFunctionCall(tidNode2, tlparNode3, null, trparNode5);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        TLPar tlparNode3;
        PArglist parglistNode4;
        TRPar trparNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        parglistNode4 = (PArglist)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);

        pfunctioncallNode1 = new AEreaFunctionCall(tidNode2, tlparNode3, parglistNode4, trparNode5);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new ADdsasaArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new ADdsasaArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaExpression pcommaexpressionNode1;
        {
        TComma tcommaNode2;
        PExpression pexpressionNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);

        pcommaexpressionNode1 = new AFrfrfrfrfeCommaExpression(tcommaNode2, pexpressionNode3);
        }
	nodeList.add(pcommaexpressionNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pcomparisonNode1 = new ATrueComparison(ttrueNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pcomparisonNode1 = new AFalseComparison(tfalseNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TLesseq tlesseqNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tlesseqNode3 = (TLesseq)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALesseqComparison(pexpressionNode2, tlesseqNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TGreateq tgreateqNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tgreateqNode3 = (TGreateq)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreateqComparison(pexpressionNode2, tgreateqNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TNoteq tnoteqNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tnoteqNode3 = (TNoteq)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ADiffComparison(pexpressionNode2, tnoteqNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TEqualequal tequalequalNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tequalequalNode3 = (TEqualequal)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqeqComparison(pexpressionNode2, tequalequalNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TLess tlessNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALesscComparison(pexpressionNode2, tlessNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        TGreat tgreatNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tgreatNode3 = (TGreat)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatcComparison(pexpressionNode2, tgreatNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PCalculation pcalculationNode2;
        pcalculationNode2 = (PCalculation)nodeArrayList1.get(0);

        pexpressionNode1 = new ACalculationExpression(pcalculationNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpressionsWithoutCulc pexpressionswithoutculcNode2;
        pexpressionswithoutculcNode2 = (PExpressionsWithoutCulc)nodeArrayList1.get(0);

        pexpressionNode1 = new AExprWCExpression(pexpressionswithoutculcNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpressionsWithoutCulc pexpressionswithoutculcNode1;
        {
        TId tidNode2;
        TLBr tlbrNode3;
        PExpression pexpressionNode4;
        TRBr trbrNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tlbrNode3 = (TLBr)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trbrNode5 = (TRBr)nodeArrayList4.get(0);

        pexpressionswithoutculcNode1 = new APinakasexpExpressionsWithoutCulc(tidNode2, tlbrNode3, pexpressionNode4, trbrNode5);
        }
	nodeList.add(pexpressionswithoutculcNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpressionsWithoutCulc pexpressionswithoutculcNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionswithoutculcNode1 = new ARedExpressionsWithoutCulc(pfunctioncallNode2);
        }
	nodeList.add(pexpressionswithoutculcNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCalculation pcalculationNode1;
        {
        PExpression pexpressionNode2;
        TPlus tplusNode3;
        PMultiplication pmultiplicationNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pmultiplicationNode4 = (PMultiplication)nodeArrayList3.get(0);

        pcalculationNode1 = new AAdditionCalculation(pexpressionNode2, tplusNode3, pmultiplicationNode4);
        }
	nodeList.add(pcalculationNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCalculation pcalculationNode1;
        {
        PExpression pexpressionNode2;
        TMinus tminusNode3;
        PMultiplication pmultiplicationNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pmultiplicationNode4 = (PMultiplication)nodeArrayList3.get(0);

        pcalculationNode1 = new ASubtractionCalculation(pexpressionNode2, tminusNode3, pmultiplicationNode4);
        }
	nodeList.add(pcalculationNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCalculation pcalculationNode1;
        {
        PMultiplication pmultiplicationNode2;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);

        pcalculationNode1 = new AMultiplicationCalculation(pmultiplicationNode2);
        }
	nodeList.add(pcalculationNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCalculation pcalculationNode1;
        {
        PExpression pexpressionNode2;
        TPlus tplusNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        pcalculationNode1 = new AAdditionExCalculation(pexpressionNode2, tplusNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(pcalculationNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCalculation pcalculationNode1;
        {
        PExpression pexpressionNode2;
        TMinus tminusNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        pcalculationNode1 = new ASubtractionExCalculation(pexpressionNode2, tminusNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(pcalculationNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PPower ppowerNode2;
        ppowerNode2 = (PPower)nodeArrayList1.get(0);

        pmultiplicationNode1 = new APowMultiplication(ppowerNode2);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TDiv tdivNode3;
        PPower ppowerNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        ppowerNode4 = (PPower)nodeArrayList3.get(0);

        pmultiplicationNode1 = new ADivisionMultiplication(pmultiplicationNode2, tdivNode3, ppowerNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TMod tmodNode3;
        PPower ppowerNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        ppowerNode4 = (PPower)nodeArrayList3.get(0);

        pmultiplicationNode1 = new AModuloMultiplication(pmultiplicationNode2, tmodNode3, ppowerNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TMult tmultNode3;
        PPower ppowerNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        ppowerNode4 = (PPower)nodeArrayList3.get(0);

        pmultiplicationNode1 = new AMultiplicationMultiplication(pmultiplicationNode2, tmultNode3, ppowerNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TDiv tdivNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        pmultiplicationNode1 = new ADivisionezMultiplication(pmultiplicationNode2, tdivNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TMod tmodNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        pmultiplicationNode1 = new AModuloezMultiplication(pmultiplicationNode2, tmodNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMultiplication pmultiplicationNode1;
        {
        PMultiplication pmultiplicationNode2;
        TMult tmultNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        pmultiplicationNode2 = (PMultiplication)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        pmultiplicationNode1 = new AMultiplicationezMultiplication(pmultiplicationNode2, tmultNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(pmultiplicationNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPower ppowerNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        ppowerNode1 = new AValuePower(pvalueNode2);
        }
	nodeList.add(ppowerNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPower ppowerNode1;
        {
        PPower ppowerNode2;
        TPow tpowNode3;
        PValue pvalueNode4;
        ppowerNode2 = (PPower)nodeArrayList1.get(0);
        tpowNode3 = (TPow)nodeArrayList2.get(0);
        pvalueNode4 = (PValue)nodeArrayList3.get(0);

        ppowerNode1 = new APowerPower(ppowerNode2, tpowNode3, pvalueNode4);
        }
	nodeList.add(ppowerNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPower ppowerNode1;
        {
        PPower ppowerNode2;
        TPow tpowNode3;
        PExpressionsWithoutCulc pexpressionswithoutculcNode4;
        ppowerNode2 = (PPower)nodeArrayList1.get(0);
        tpowNode3 = (TPow)nodeArrayList2.get(0);
        pexpressionswithoutculcNode4 = (PExpressionsWithoutCulc)nodeArrayList3.get(0);

        ppowerNode1 = new APowe2rPower(ppowerNode2, tpowNode3, pexpressionswithoutculcNode4);
        }
	nodeList.add(ppowerNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pvalueNode1 = new AIdentifierValue(tidNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumbValue(tnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TStringDoubleQuotes tstringdoublequotesNode2;
        tstringdoublequotesNode2 = (TStringDoubleQuotes)nodeArrayList1.get(0);

        pvalueNode1 = new ADValue(tstringdoublequotesNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TStringSingleQuotes tstringsinglequotesNode2;
        tstringsinglequotesNode2 = (TStringSingleQuotes)nodeArrayList1.get(0);

        pvalueNode1 = new AWeValue(tstringsinglequotesNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNone tnoneNode2;
        tnoneNode2 = (TNone)nodeArrayList1.get(0);

        pvalueNode1 = new ANonenonegoodValue(tnoneNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCiav pciavNode1;
        pciavNode1 = (PCiav)nodeArrayList1.get(0);
	if(pciavNode1 != null)
	{
	  listNode2.add(pciavNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCiav pciavNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pciavNode2 = (PCiav)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pciavNode2 != null)
	{
	  listNode3.add(pciavNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaExpression pcommaexpressionNode1;
        pcommaexpressionNode1 = (PCommaExpression)nodeArrayList1.get(0);
	if(pcommaexpressionNode1 != null)
	{
	  listNode2.add(pcommaexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaExpression pcommaexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommaexpressionNode2 = (PCommaExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommaexpressionNode2 != null)
	{
	  listNode3.add(pcommaexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {15, SHIFT, 2}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, REDUCE, 80}, },
			{{-1, ERROR, 2}, {48, SHIFT, 16}, },
			{{-1, ERROR, 3}, {39, SHIFT, 17}, {41, SHIFT, 18}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 4}, {39, SHIFT, 17}, {41, SHIFT, 18}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 5}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 6}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 7}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 8}, {4, SHIFT, 36}, {6, SHIFT, 37}, {14, SHIFT, 38}, {19, SHIFT, 39}, {21, SHIFT, 40}, {24, SHIFT, 41}, },
			{{-1, ERROR, 9}, {52, ACCEPT, -1}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {15, SHIFT, 2}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 15}, {0, SHIFT, 43}, {25, SHIFT, 44}, {26, SHIFT, 45}, {31, SHIFT, 46}, {32, SHIFT, 47}, {33, SHIFT, 48}, {48, SHIFT, 49}, },
			{{-1, ERROR, 16}, {21, SHIFT, 51}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 71}, {19, SHIFT, 52}, {21, SHIFT, 40}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 74}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 25}, {40, SHIFT, 53}, },
			{{-1, ERROR, 26}, {2, SHIFT, 54}, {8, SHIFT, 55}, {9, SHIFT, 56}, {34, SHIFT, 57}, {35, SHIFT, 58}, {36, SHIFT, 59}, {37, SHIFT, 60}, {38, SHIFT, 61}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 58}, {11, SHIFT, 62}, {12, SHIFT, 63}, {13, SHIFT, 64}, },
			{{-1, REDUCE, 61}, {10, SHIFT, 65}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 32}, {40, SHIFT, 66}, },
			{{-1, REDUCE, 21}, {8, SHIFT, 55}, {9, SHIFT, 56}, {23, SHIFT, 67}, },
			{{-1, REDUCE, 19}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 33}, {8, SHIFT, 55}, {9, SHIFT, 56}, {23, SHIFT, 67}, },
			{{-1, ERROR, 36}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 37}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 38}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 39}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 40}, {22, SHIFT, 74}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 41}, {48, SHIFT, 77}, },
			{{-1, REDUCE, 77}, },
			{{-1, REDUCE, 81}, },
			{{-1, ERROR, 44}, {39, SHIFT, 17}, {41, SHIFT, 18}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 45}, {39, SHIFT, 17}, {41, SHIFT, 18}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 46}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 47}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 48}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 49}, {4, SHIFT, 83}, {6, SHIFT, 84}, {14, SHIFT, 85}, {19, SHIFT, 86}, {21, SHIFT, 40}, {24, SHIFT, 87}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 51}, {22, SHIFT, 88}, {48, SHIFT, 89}, },
			{{-1, ERROR, 52}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 53}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 54}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 55}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 56}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 57}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 58}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 59}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 60}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 61}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 62}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 63}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 64}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 65}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 66}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 67}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 27}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 29}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 25}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, ERROR, 73}, {8, SHIFT, 55}, {9, SHIFT, 56}, {20, SHIFT, 113}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 75}, {22, SHIFT, 114}, },
			{{-1, REDUCE, 41}, {8, SHIFT, 55}, {9, SHIFT, 56}, {23, SHIFT, 67}, },
			{{-1, ERROR, 77}, {40, SHIFT, 117}, },
			{{-1, ERROR, 78}, {40, SHIFT, 118}, },
			{{-1, ERROR, 79}, {40, SHIFT, 119}, },
			{{-1, REDUCE, 22}, {8, SHIFT, 55}, {9, SHIFT, 56}, {23, SHIFT, 67}, },
			{{-1, REDUCE, 20}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 34}, {8, SHIFT, 55}, {9, SHIFT, 56}, {23, SHIFT, 67}, },
			{{-1, ERROR, 83}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 84}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 85}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 86}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 87}, {48, SHIFT, 126}, },
			{{-1, ERROR, 88}, {40, SHIFT, 127}, },
			{{-1, REDUCE, 6}, {14, SHIFT, 128}, {23, SHIFT, 129}, },
			{{-1, ERROR, 90}, {22, SHIFT, 133}, },
			{{-1, ERROR, 91}, {8, SHIFT, 55}, {9, SHIFT, 56}, {20, SHIFT, 134}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 49}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 56}, {11, SHIFT, 62}, {12, SHIFT, 63}, {13, SHIFT, 64}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 57}, {11, SHIFT, 62}, {12, SHIFT, 63}, {13, SHIFT, 64}, },
			{{-1, REDUCE, 48}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 46}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 47}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 50}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 51}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 64}, {10, SHIFT, 65}, },
			{{-1, REDUCE, 66}, },
			{{-1, REDUCE, 63}, {10, SHIFT, 65}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 62}, {10, SHIFT, 65}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 43}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, ERROR, 113}, {14, SHIFT, 135}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 82}, },
			{{-1, REDUCE, 42}, {23, SHIFT, 67}, },
			{{-1, ERROR, 117}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 118}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 119}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 28}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 30}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, REDUCE, 26}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, ERROR, 125}, {8, SHIFT, 55}, {9, SHIFT, 56}, {20, SHIFT, 140}, },
			{{-1, ERROR, 126}, {40, SHIFT, 141}, },
			{{-1, ERROR, 127}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, ERROR, 128}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 143}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, ERROR, 129}, {48, SHIFT, 145}, },
			{{-1, REDUCE, 78}, },
			{{-1, REDUCE, 7}, {23, SHIFT, 129}, },
			{{-1, REDUCE, 8}, {23, SHIFT, 129}, },
			{{-1, ERROR, 133}, {40, SHIFT, 148}, },
			{{-1, REDUCE, 54}, },
			{{-1, ERROR, 135}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, REDUCE, 83}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 140}, {14, SHIFT, 150}, },
			{{-1, ERROR, 141}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 10}, {14, SHIFT, 128}, },
			{{-1, REDUCE, 9}, {23, SHIFT, 129}, },
			{{-1, REDUCE, 79}, },
			{{-1, ERROR, 148}, {0, SHIFT, 1}, {25, SHIFT, 3}, {26, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {48, SHIFT, 8}, },
			{{-1, REDUCE, 31}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
			{{-1, ERROR, 150}, {43, SHIFT, 19}, {46, SHIFT, 20}, {48, SHIFT, 21}, {49, SHIFT, 22}, {50, SHIFT, 23}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 32}, {8, SHIFT, 55}, {9, SHIFT, 56}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 9}, },
			{{-1, 10}, {14, 42}, },
			{{-1, 11}, },
			{{-1, 90}, },
			{{-1, 130}, {132, 147}, {146, 147}, },
			{{-1, 131}, {145, 152}, },
			{{-1, 12}, {53, 92}, {66, 111}, {117, 137}, {118, 138}, {119, 139}, {127, 142}, {141, 151}, {148, 153}, },
			{{-1, 24}, {0, 13}, {14, 13}, {15, 50}, {53, 13}, {66, 13}, {117, 13}, {118, 13}, {119, 13}, {127, 13}, {141, 13}, {148, 13}, },
			{{-1, 75}, },
			{{-1, 68}, {35, 69}, {76, 115}, {80, 120}, {82, 121}, {116, 136}, },
			{{-1, 25}, {4, 32}, {44, 78}, {45, 79}, },
			{{-1, 26}, {5, 33}, {6, 34}, {7, 35}, {36, 70}, {37, 71}, {38, 72}, {39, 73}, {40, 76}, {46, 80}, {47, 81}, {48, 82}, {52, 91}, {54, 93}, {57, 98}, {58, 99}, {59, 100}, {60, 101}, {61, 102}, {67, 112}, {83, 122}, {84, 123}, {85, 124}, {86, 125}, {135, 149}, {150, 154}, },
			{{-1, 27}, {55, 94}, {56, 96}, {62, 103}, {63, 105}, {64, 107}, {65, 109}, },
			{{-1, 28}, },
			{{-1, 29}, {55, 95}, {56, 97}, },
			{{-1, 30}, {62, 104}, {63, 106}, {64, 108}, },
			{{-1, 31}, {65, 110}, {128, 144}, },
			{{-1, 14}, },
			{{-1, 132}, {131, 146}, },
			{{-1, 15}, },
			{{-1, 116}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, 'if', 'while', 'print', 'return', 'assert', id",
			"expecting: id",
			"expecting: 'true', 'false', 'None', number, id, string double quotes, string single quotes",
			"expecting: 'None', number, id, string double quotes, string single quotes",
			"expecting: '-=', '/=', '=', '[', '(', 'in'",
			"expecting: EOF",
			"expecting: '('",
			"expecting: ':'",
			"expecting: tab, '==', '+', '-', '**', '*', '%', '/', 'def', ']', ')', ',', 'if', 'while', 'print', 'return', 'assert', '!=', '<=', '>=', '<', '>', ':', id, EOF",
			"expecting: tab, '==', '+', '-', '**', '*', '%', '/', 'def', '[', ']', '(', ')', ',', 'if', 'while', 'print', 'return', 'assert', '!=', '<=', '>=', '<', '>', ':', id, EOF",
			"expecting: '==', '+', '-', '!=', '<=', '>=', '<', '>'",
			"expecting: tab, '==', '+', '-', 'def', ']', ')', ',', 'if', 'while', 'print', 'return', 'assert', '!=', '<=', '>=', '<', '>', ':', id, EOF",
			"expecting: tab, '==', '+', '-', '*', '%', '/', 'def', ']', ')', ',', 'if', 'while', 'print', 'return', 'assert', '!=', '<=', '>=', '<', '>', ':', id, EOF",
			"expecting: tab, '+', '-', 'def', ',', 'if', 'while', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, '+', '-', 'def', 'if', 'while', 'print', 'return', 'assert', id, EOF",
			"expecting: ')', 'None', number, id, string double quotes, string single quotes",
			"expecting: ')', id",
			"expecting: '+', '-', ']'",
			"expecting: ')'",
			"expecting: '+', '-', ')', ','",
			"expecting: '=', ')', ','",
			"expecting: '+', '-', ':'",
			"expecting: tab, '+', '-', 'def', ')', ',', 'if', 'while', 'print', 'return', 'assert', id, EOF",
			"expecting: '='",
			"expecting: ')', ','",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 4, 4, 5, 6, 0, 0, 0, 0, 0, 1, 7, 8, 8, 9, 9, 10, 9, 9, 9, 8, 11, 12, 12, 13, 9, 9, 8, 14, 15, 14, 4, 4, 4, 4, 16, 2, 0, 1, 3, 3, 4, 4, 4, 5, 0, 17, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 0, 0, 15, 15, 15, 18, 9, 19, 20, 8, 8, 8, 14, 15, 14, 4, 4, 4, 4, 2, 8, 21, 19, 18, 0, 22, 12, 13, 12, 13, 22, 22, 22, 22, 22, 13, 9, 13, 9, 13, 9, 9, 9, 0, 23, 24, 9, 25, 25, 1, 1, 1, 0, 0, 15, 15, 15, 18, 8, 1, 4, 2, 25, 25, 25, 8, 9, 4, 25, 0, 0, 0, 24, 1, 0, 25, 25, 21, 25, 25, 1, 15, 4, 0, 25, 0, 15, 
        };*/
}
